substitutions:
  devicename: hub
  comment: ""

esphome:
  name: $devicename
  comment: $comment
  platform: ESP8266
  board: d1_mini
  includes:
  - lib/EspRC.h
  - lib/esp_now_light.h

wifi:
  networks:
  reboot_timeout: 300s

logger:

api:
  services:
    - service: restart_node
      then:
        - switch.turn_on: restartswitch

ota:
  password: $devicename !secret otapass

switch:
  - platform: restart
    id: restartswitch

light:
- platform: custom
  lambda: |-
    auto light_out_1 = new esp_now_light("ball_1");
    auto light_out_2 = new esp_now_light("ball_2");
    App.register_component(light_out_1);
    App.register_component(light_out_2);
    return {light_out_1, light_out_2};
  lights:
    - name: "Custom Light 1"
    - name: "Custom Light 2"

sensor:
  - platform: wifi_signal
    name: ${devicename} WiFi Signal Sensor
    unit_of_measurement: "%"
    filters:
    - lambda: |-
        if(x <= -100){
          return  0;
        } else if (x >= -50) {
          return 100;
        } else {
          return 2 * (x + 100);
        }
